name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: 1.准备环境
        run: |
          echo UMIPKG=11111 >> "$GITHUB_WORKSPACE"/romdata/UMI.ini
          echo UMIMD5=22222 >> "$GITHUB_WORKSPACE"/romdata/UMI.ini
          echo UMITIME=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d %H:%M') >> "$GITHUB_WORKSPACE"/romdata/UMI.ini
      - name: 9.导出信息
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'romdata/UMI.ini'
          destination_repo: 'zjw2017/sm8250-page'
          destination_folder: 'device'
          user_email: 'example@email.com'
          user_name: 'zjw2017'
          commit_message: 'Update from $GITHUB_REF'
